
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

#includes
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
